export const imagesf = {
    "https://flagcdn.com/al.svg": "Albania",
    "https://flagcdn.com/w160/ad.jpg": "Andorra",
    "https://flagcdn.com/ch.svg": "Switzerland",
    "https://flagcdn.com/va.svg": "Vatican",
    "https://flagcdn.com/is.svg": "Iceland",
    "https://flagcdn.com/mc.svg": "Monaco",
    "https://flagcdn.com/sm.svg": "San Marino",
    "https://flagcdn.com/at.svg": "Austria",
    "https://flagcdn.com/by.svg": "Belarus",
    "https://flagcdn.com/ba.svg": "Bosnia and Herzegovina",
    "https://flagcdn.com/bg.svg": "Bulgaria",
    "https://flagcdn.com/ee.svg": "Estonia",
    "https://flagcdn.com/fi.svg": "Finland",
    "https://flagcdn.com/ie.svg": "Ireland",
    "https://flagcdn.com/it.svg": "Italy",
    "https://flagcdn.com/kz.svg": "Kazakhstan",
    "https://flagcdn.com/lv.svg": "Latvia",
    "https://flagcdn.com/li.svg": "Liechtenstein",
    "https://flagcdn.com/lt.svg": "Lithuania",
    "https://flagcdn.com/lu.svg": "Luxembourg",
    "https://flagcdn.com/ro.svg": "Romania",
    "https://flagcdn.com/rs.svg": "Serbia",
    "https://flagcdn.com/w160/sk.jpg": "Slovakia",
    "https://flagcdn.com/si.svg": "Slovenia",
    "https://flagcdn.com/es.svg": "Spain",
    "https://flagcdn.com/se.svg": "Sweden",
    "https://flagcdn.com/cz.svg": "Czech Republic",
    "https://flagcdn.com/nl.svg": "Netherlands",
    "https://flagcdn.com/gb.svg": "United Kingdom",
    "https://flagcdn.com/ua.svg": "Ukraine",
    "https://flagcdn.com/be.svg": "Belgium",
    "https://flagcdn.com/hr.svg": "Croatia",
    "https://flagcdn.com/dk.svg": "Denmark",
    "https://flagcdn.com/fr.svg": "France",
    "https://flagcdn.com/de.svg": "Germany",
    "https://flagcdn.com/gr.svg": "Greece",
    "https://flagcdn.com/hu.svg": "Hungary",
    "https://flagcdn.com/mt.svg": "Malta",
    "https://flagcdn.com/md.svg": "Moldova",
    "https://flagcdn.com/me.svg": "Montenegro",
    "https://flagcdn.com/mk.svg": "North Macedonia",
    "https://flagcdn.com/no.svg": "Norway",
    "https://flagcdn.com/pl.svg": "Poland",
    "https://flagcdn.com/pt.svg": "Portugal",
    "https://flagcdn.com/ru.svg": "Russia",
    "https://flagcdn.com/tr.svg": "Turkey"
  };