export const imagesf = {"flagi\\Flag_of_Albania.svg.png":"Albania",
                        "flagi\\Flag_of_Andorra.svg.png":"Andorra",
                        "flagi\\1024px-Flag_of_Switzerland.svg.png":"Switzerland",
                        "flagi\\1024px-Flag_of_the_Vatican_City.svg.png":"Vatican",
                        "flagi\\1280px-Flag_of_Iceland.svg.png":"Iceland",
                        "flagi\\1280px-Flag_of_Monaco.svg.png":"Monaco",
                        "flagi\\1280px-Flag_of_San_Marino.svg.png":"San Marino",
                        "flagi\\1920px-Flag_of_Austria.svg.png":"Austria",
                        "flagi\\1920px-Flag_of_Belarus.svg.png":"Belarus",
                        "flagi\\1920px-Flag_of_Bosnia_and_Herzegovina.svg.png":"Bosnia and Herzegovina",
                        "flagi\\1920px-Flag_of_Bulgaria.svg.png":"Bulgaria",
                        "flagi\\1920px-Flag_of_Estonia.svg.png":"Estonia",
                        "flagi\\1920px-Flag_of_Finland.svg.png":"Finland",
                        "flagi\\1920px-Flag_of_Ireland.svg.png":"Ireland",
                        "flagi\\1920px-Flag_of_Italy.svg.png":"Italy",
                        "flagi\\1920px-Flag_of_Kazakhstan.svg.png":"Kazakhstan",
                        "flagi\\1920px-Flag_of_Latvia.svg.png":"Latvia",
                        "flagi\\1920px-Flag_of_Liechtenstein.svg.png":"Liechtenstein",
                        "flagi\\1920px-Flag_of_Lithuania.svg.png":"Lithuania",
                        "flagi\\1920px-Flag_of_Luxembourg.svg.png":"Luxembourg",
                        "flagi\\1920px-Flag_of_Romania.svg.png":"Romania",
                        "flagi\\1920px-Flag_of_Serbia.svg.png":"Serbia",
                        "flagi\\1920px-Flag_of_Slovakia.svg.png":"Slovakia",
                        "flagi\\1920px-Flag_of_Slovenia.svg.png":"Slovenia",
                        "flagi\\1920px-Flag_of_Spain.svg.png":"Spain",
                        "flagi\\1920px-Flag_of_Sweden.svg.png":"Sweden",
                        "flagi\\1920px-Flag_of_the_Czech_Republic.svg.png":"Czech Republic",
                        "flagi\\1920px-Flag_of_the_Netherlands.svg.png":"Netherlands",
                        "flagi\\1920px-Flag_of_the_United_Kingdom.svg.png":"United Kingdom",
                        "flagi\\1920px-Flag_of_Ukraine.svg.png":"Ukraine",
                        "flagi\\Flag_of_Belgium.svg.png":"Belgium",
                        "flagi\\Flag_of_Croatia.svg.png":"Croatia",
                        "flagi\\Flag_of_Denmark.svg.png":"Denmark",
                        "flagi\\Flag_of_France.svg.png":"France",
                        "flagi\\Flag_of_Germany.svg.png":"Germany",
                        "flagi\\Flag_of_Greece.svg.png":"Greece",
                        "flagi\\Flag_of_Hungary.svg.png":"Hungary",
                        "flagi\\Flag_of_Malta.svg.png":"Malta",
                        "flagi\\Flag_of_Moldova.svg.png":"Moldova",
                        "flagi\\Flag_of_Montenegro.svg.png":"Montenegro",
                        "flagi\\Flag_of_North_Macedonia.svg.png":"North Macedonia",
                        "flagi\\Flag_of_Norway.svg.png":"Norway",
                        "flagi\\Flag_of_Poland.svg.png":"Poland",
                        "flagi\\Flag_of_Portugal.svg.png":"Portugal",
                        "flagi\\Flag_of_Russia.svg.png":"Russia",
                        "flagi\\Flag_of_Turkey.svg.png":"Turkey"}
